# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 419e16d8f95a29d5e06d8a96a59c3bfb25bb8533e84ef2194b74122670a14d982ea47acfd58fc9a2f52dea33ef6fb47a6aed3bf6ac3c680ee67d4f65f32344d4

test:
  secret_key_base: 74ce3842e7db54a6789d01e1e9a66e71e8cef4002c156e226c84ca1f9172b30bfdbe1f0063bdb12161f3c9f1a80050f7874daa8a217c8db81f5c001b816ee6f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
